#!/usr/bin/env python3
"""Genriert registry/framework.yaml — den Enterprise-Katalog (ATC-STD-FRAMEWORK-001 §5).
SSOT der Slot-Zuordnung; Regenerierung nur via SCR (REQ-FW-012)."""
import yaml

S_NEU, S_BELEGT, S_VERWEIST, S_KONFLIKT, S_GEPLANT = "NEU", "BELEGT", "VERWEIST", "KONFLIKT", "GEPLANT"

def F(fid, name, rng, slots, note=None, frefs=None):
    return {"id": fid, "name": name, "range": rng, "note": note, "family_refs": frefs, "slots": slots}

def sl(sid, title, status=S_NEU, refs=None, note=None):
    s = {"id": sid, "title": title, "status": status}
    if refs: s["refs"] = refs
    if note: s["note"] = note
    return s

SC = [f"ATC-STD-SC-{i:03d}" for i in range(1, 21)]
ZKP = [f"ATC-STD-ZKP-{i:03d}" for i in range(1, 11)]
AAS = [f"ATC-AAS-{i:03d}" for i in range(1, 26)]

FAMILIES = [
F("FAM-01", "Enterprise & Governance", "ATC-STD-001..015", [
    sl("ATC-STD-001", "Enterprise Governance Standard"),
    sl("ATC-STD-002", "Organisationsstruktur Standard", S_VERWEIST, [f"ATC-ENT-{i:03d}" for i in range(1, 16)], "Enterprise Layer ATC-ENT-001..015 als Basis"),
    sl("ATC-STD-003", "Rollen & Verantwortlichkeiten", S_VERWEIST, ["ATC-STD-000"], "§14.1 Rollenmodell"),
    sl("ATC-STD-004", "Entscheidungsfindungsstandard", S_VERWEIST, ["ATC-STD-000"], "§9 + AD-Register"),
    sl("ATC-STD-005", "Authority & Permission Standard", S_VERWEIST, ["ATC-STD-000"], "§14.1"),
    sl("ATC-STD-006", "Policy Management"),
    sl("ATC-STD-007", "Risk Management", S_VERWEIST, ["ATC-STD-MILESTONE-001"], "§12 Risikomodell je Meilenstein; Org-Ebene offen"),
    sl("ATC-STD-008", "Compliance Management"),
    sl("ATC-STD-009", "Audit Standard", S_VERWEIST, ["ATC-STD-AUDIT-001"]),
    sl("ATC-STD-010", "Vollständigkeitsprüfungs-Audit", S_VERWEIST, ["ATC-STD-AUDIT-001"]),
    sl("ATC-STD-011", "Change Governance", S_VERWEIST, ["ATC-STD-000", "ATC-STD-UPDATE-001"], "§19-33 SCR + UPD-Lifecycle"),
    sl("ATC-STD-012", "Incident Governance"),
    sl("ATC-STD-013", "Escalation Standard"),
    sl("ATC-STD-014", "Evidence & Traceability", S_VERWEIST, ["ATC-STD-BUG-005", "ATC-STD-MILESTONE-001"], "BUG-005 Evidence + MILESTONE-001 §6 Evidence Packs"),
    sl("ATC-STD-015", "Records Management"),
]),
F("FAM-02", "Standards-Governance", "ATC-STD-020..033", [
    sl("ATC-STD-020", "Standards Lifecycle", S_VERWEIST, ["ATC-STD-000"], "§11/§13"),
    sl("ATC-STD-021", "Standards Registry", S_VERWEIST, ["ATC-STD-000"], "§7 Registry-Pflicht"),
    sl("ATC-STD-022", "Standards Naming", S_VERWEIST, ["ATC-STD-000"], "§7 Naming, naming-conventions.schema.json"),
    sl("ATC-STD-023", "Standards Versionierung", S_VERWEIST, ["ATC-STD-VERSION-001"]),
    sl("ATC-STD-024", "Standards Status", S_VERWEIST, ["ATC-STD-000"], "§11 Lifecycle"),
    sl("ATC-STD-025", "Standards Review", S_NEU, None, "Review-Kadenzen teils in UPDATE-001; eigenständig bei Bedarf"),
    sl("ATC-STD-026", "Standards Approval", S_VERWEIST, ["ATC-STD-000"], "§9 Freigabe"),
    sl("ATC-STD-027", "Standards Deprecation", S_NEU, None, "Deprecation-Pfad in ATC-STD-000 §11; Ausprägung offen"),
    sl("ATC-STD-028", "Standards Compatibility", S_VERWEIST, ["ATC-STD-COMPAT-001"]),
    sl("ATC-STD-029", "Standards Change Request", S_VERWEIST, ["ATC-STD-000"], "§19-33 SCR-Prozess"),
    sl("ATC-STD-030", "Standards Conflict Resolution", S_VERWEIST, ["ATC-STD-000"]),
    sl("ATC-STD-031", "Standards Dependency Management", S_VERWEIST, ["ATC-STD-204"], "registry/dependencies.yaml DAG"),
    sl("ATC-STD-032", "Standards Traceability", S_VERWEIST, ["ATC-STD-AUDIT-001"]),
    sl("ATC-STD-033", "Standards Audit", S_VERWEIST, ["ATC-STD-AUDIT-001"]),
]),
F("FAM-03", "Repository Standards", "ATC-STD-040..054", [
    sl("ATC-STD-040", "Repository Architecture"),
    sl("ATC-STD-041", "Repository Naming", S_VERWEIST, ["ATC-STD-202"]),
    sl("ATC-STD-042", "Repository Ownership"),
    sl("ATC-STD-043", "Repository README", S_VERWEIST, ["ATC-STD-README-001"]),
    sl("ATC-STD-044", "Repository Structure", S_VERWEIST, ["ATC-STD-201"]),
    sl("ATC-STD-045", "Repository Metadata"),
    sl("ATC-STD-046", "Repository Documentation", S_VERWEIST, ["ATC-STD-MD-001"]),
    sl("ATC-STD-047", "Repository Security", S_VERWEIST, ["ATC-STD-203"]),
    sl("ATC-STD-048", "Repository Branching"),
    sl("ATC-STD-049", "Repository Permissions", S_VERWEIST, ["ATC-STD-203"], "Security & Release-Teilabdeckung; Org-Settings F-024 SKIP"),
    sl("ATC-STD-050", "Repository Archiving"),
    sl("ATC-STD-051", "Repository Deprecation"),
    sl("ATC-STD-052", "Repository Health"),
    sl("ATC-STD-053", "Repository Dependency Management", S_VERWEIST, ["ATC-STD-204"]),
    sl("ATC-STD-054", "Repository Completeness", S_VERWEIST, ["ATC-STD-AUDIT-001"], "MD-001 REQ-MD-001 als Teilbasis"),
]),
F("FAM-04", "Dokumentationsstandards", "ATC-STD-060..075", [
    sl("ATC-STD-060", "Documentation Standard", S_VERWEIST, ["ATC-STD-MD-001"]),
    sl("ATC-STD-061", "README Standard", S_VERWEIST, ["ATC-STD-README-001"]),
    sl("ATC-STD-062", "Wiki Standard", S_NEU, None, "Alte Wiki-Struktur archiviert; künftiges Wissens-Management"),
    sl("ATC-STD-063", "API Documentation"),
    sl("ATC-STD-064", "Architecture Documentation"),
    sl("ATC-STD-065", "Specification Standard", S_VERWEIST, ["ATC-STD-DESC-001"]),
    sl("ATC-STD-066", "Whitepaper Standard"),
    sl("ATC-STD-067", "Technical Paper Standard"),
    sl("ATC-STD-068", "CHANGELOG Standard", S_VERWEIST, ["ATC-STD-VERSION-001", "ATC-STD-UPDATE-001"]),
    sl("ATC-STD-069", "Release Notes"),
    sl("ATC-STD-070", "TODO Standard"),
    sl("ATC-STD-071", "Roadmap Standard", S_VERWEIST, ["ATC-STD-MILESTONE-001"], "§9 Roadmap→Milestone; AD-027"),
    sl("ATC-STD-072", "Sprint Documentation"),
    sl("ATC-STD-073", "Decision Log", S_VERWEIST, ["ATC-STD-000"], "AD-Register als Bestands-Implementierung"),
    sl("ATC-STD-074", "ADR Standard", S_VERWEIST, ["ATC-STD-000"], "AD-System (AD-001..046)"),
    sl("ATC-STD-075", "Documentation Synchronisation", S_VERWEIST, ["ATC-STD-AUDIT-001"], "Cross-System-Integrität"),
]),
F("FAM-05", "Software Development", "ATC-STD-080..095", [
    sl("ATC-STD-080", "Software Development Lifecycle", S_VERWEIST, ["ATC-STD-UPDATE-001"], "UPD-Lifecycle als Change-Sicht; SDLC-Ausprägung offen"),
    sl("ATC-STD-081", "Coding Standard"),
    sl("ATC-STD-082", "Code Style"),
    sl("ATC-STD-083", "Naming Convention", S_VERWEIST, ["ATC-STD-000"], "§7 Naming + Repo-NAMING_CONVENTIONS"),
    sl("ATC-STD-084", "Architecture Standard", S_BELEGT, ["ATC-STD-100"], "ATC-STD-100 ist der Architecture Standard"),
    sl("ATC-STD-085", "Modularisation"),
    sl("ATC-STD-086", "Dependency Standard", S_VERWEIST, ["ATC-STD-204"]),
    sl("ATC-STD-087", "Error Handling"),
    sl("ATC-STD-088", "Logging"),
    sl("ATC-STD-089", "Configuration Management"),
    sl("ATC-STD-090", "Environment Management"),
    sl("ATC-STD-091", "Testing"),
    sl("ATC-STD-092", "Code Review", S_VERWEIST, ["ATC-STD-BUG-004"], "Merge-Gate-Teilabdeckung"),
    sl("ATC-STD-093", "Refactoring"),
    sl("ATC-STD-094", "Technical Debt"),
    sl("ATC-STD-095", "Build Standard"),
]),
F("FAM-06", "Git & Version Control", "ATC-STD-100..113", [
    sl("ATC-STD-100", "Git Standard", S_KONFLIKT, None, "Slot belegt durch ATC-STD-100 (Architecture Standard, §30-eingefroren). Auflösung via SCR: Git-Familie auf freie Slots/Namensraum legen (Empfehlung SCR-0019 §6.2)"),
    sl("ATC-STD-101", "Branch Naming"),
    sl("ATC-STD-102", "Commit Naming", S_VERWEIST, ["ATC-STD-202"], "Commit-Trailer-Konventionen teils in 202/UPDATE-001"),
    sl("ATC-STD-103", "Commit Message"),
    sl("ATC-STD-104", "Pull Request"),
    sl("ATC-STD-105", "Merge Policy"),
    sl("ATC-STD-106", "Branch Protection", S_VERWEIST, ["ATC-STD-203"], "SCR-0003 umgesetzt (Branch-Protection aktiv)"),
    sl("ATC-STD-107", "Tagging"),
    sl("ATC-STD-108", "Release Management", S_VERWEIST, ["ATC-STD-VERSION-001"]),
    sl("ATC-STD-109", "Semantic Versioning", S_VERWEIST, ["ATC-STD-VERSION-001"]),
    sl("ATC-STD-110", "Major-Version Migration", S_VERWEIST, ["ATC-STD-UPDATE-001", "ATC-STD-COMPAT-001"], "UPD-G04 + MAJOR-Gate"),
    sl("ATC-STD-111", "Backward Compatibility", S_VERWEIST, ["ATC-STD-COMPAT-001"]),
    sl("ATC-STD-112", "Rollback", S_VERWEIST, ["ATC-STD-UPDATE-001"]),
    sl("ATC-STD-113", "Release Verification", S_VERWEIST, ["ATC-STD-UPDATE-001"], "UPD Post-Release-Audit"),
]),
F("FAM-07", "Bug & Fehler-Management", "ATC-STD-120..131", [
    sl("ATC-STD-120", "Bug Management", S_VERWEIST, ["ATC-STD-BUG-001", "ATC-STD-BUG-003"]),
    sl("ATC-STD-121", "Bug Detection", S_VERWEIST, ["ATC-STD-BUG-001"]),
    sl("ATC-STD-122", "Bug Classification", S_VERWEIST, ["ATC-STD-BUG-001", "ATC-STD-BUG-005"], "RC-Kategorien in BUG-005"),
    sl("ATC-STD-123", "Bug Documentation", S_VERWEIST, ["ATC-STD-BUG-002"]),
    sl("ATC-STD-124", "Root Cause Analysis", S_VERWEIST, ["ATC-STD-BUG-005"], "4-Ebenen-RCA, Fault Tree, Timeline, Metrics"),
    sl("ATC-STD-125", "Bug Prioritisation", S_VERWEIST, ["ATC-STD-BUG-005"], "Impact/Priority-Felder"),
    sl("ATC-STD-126", "Bug Fix", S_VERWEIST, ["ATC-STD-BUG-003"]),
    sl("ATC-STD-127", "Regression Testing", S_VERWEIST, ["ATC-STD-BUG-005", "ATC-STD-UPDATE-001"]),
    sl("ATC-STD-128", "Fix Verification", S_VERWEIST, ["ATC-STD-BUG-005"], "Closure Gate"),
    sl("ATC-STD-129", "Incident Correlation"),
    sl("ATC-STD-130", "Post-Incident Review"),
    sl("ATC-STD-131", "Code/Wiki/Repository Consistency Check", S_VERWEIST, ["ATC-STD-BUG-004", "ATC-STD-AUDIT-001"]),
]),
F("FAM-08", "Testing & Quality Assurance", "ATC-STD-140..153", [
    sl("ATC-STD-140", "QA Framework"),
    sl("ATC-STD-141", "Unit Testing"),
    sl("ATC-STD-142", "Integration Testing"),
    sl("ATC-STD-143", "System Testing"),
    sl("ATC-STD-144", "End-to-End Testing"),
    sl("ATC-STD-145", "Regression Testing", S_VERWEIST, ["ATC-STD-UPDATE-001"]),
    sl("ATC-STD-146", "Performance Testing"),
    sl("ATC-STD-147", "Load Testing"),
    sl("ATC-STD-148", "Stress Testing"),
    sl("ATC-STD-149", "Security Testing"),
    sl("ATC-STD-150", "Acceptance Testing", S_VERWEIST, ["ATC-STD-MILESTONE-001"], "§7 Acceptance Gate"),
    sl("ATC-STD-151", "Release Gate", S_VERWEIST, ["ATC-STD-UPDATE-001"], "UPD-G01..G09"),
    sl("ATC-STD-152", "Quality Gate", S_VERWEIST, ["ATC-STD-UPDATE-001", "ATC-STD-MILESTONE-001"]),
    sl("ATC-STD-153", "Test Evidence", S_VERWEIST, ["ATC-STD-MILESTONE-001"], "§6 Evidence Packs"),
]),
F("FAM-09", "CI/CD & DevOps", "ATC-STD-160..174", [
    sl("ATC-STD-160", "CI/CD", S_NEU, None, "governance-ci + validator-Workflows existieren als Bestandspraxis"),
    sl("ATC-STD-161", "Automated Build"),
    sl("ATC-STD-162", "Automated Testing", S_VERWEIST, ["ATC-STD-AUDIT-001"], "Validator-Suite als Bestandspraxis"),
    sl("ATC-STD-163", "Artifact Management"),
    sl("ATC-STD-164", "Deployment"),
    sl("ATC-STD-165", "Environment Promotion", S_VERWEIST, ["ATC-STD-NET-001"], "NET-Familie: Devnet/Testnet/Mainnet"),
    sl("ATC-STD-166", "Devnet Deployment", S_VERWEIST, ["ATC-STD-NET-002"]),
    sl("ATC-STD-167", "Testnet Deployment", S_VERWEIST, ["ATC-STD-NET-002"]),
    sl("ATC-STD-168", "Mainnet Deployment", S_VERWEIST, ["ATC-STD-NET-002", "ATC-STD-NET-003"]),
    sl("ATC-STD-169", "Infrastructure as Code"),
    sl("ATC-STD-170", "Container Standard"),
    sl("ATC-STD-171", "Kubernetes Standard"),
    sl("ATC-STD-172", "Terraform Standard"),
    sl("ATC-STD-173", "Secrets Management", S_VERWEIST, ["ATC-STD-203"], "Secret-Scanning aktiv (AUD-2026-0002); Ausprägung offen"),
    sl("ATC-STD-174", "Disaster Recovery"),
]),
F("FAM-10", "Release Readiness (RR-Gates)", "RR-G01..RR-G08", [
    sl("RR-G01", "Repository & Build", S_VERWEIST, ["ATC-STD-201"], "FRAMEWORK-001 §7"),
    sl("RR-G02", "Unit Tests", S_VERWEIST, ["ATC-STD-UPDATE-001"]),
    sl("RR-G03", "Integration", S_VERWEIST, ["ATC-STD-UPDATE-001"]),
    sl("RR-G04", "System", S_VERWEIST, ["ATC-STD-MILESTONE-001"]),
    sl("RR-G05", "Security", S_VERWEIST, ["ATC-STD-AUDIT-001"]),
    sl("RR-G06", "Performance"),
    sl("RR-G07", "Deployment", S_VERWEIST, ["ATC-STD-UPDATE-001"]),
    sl("RR-G08", "Production Ready", S_VERWEIST, ["ATC-STD-MILESTONE-001", "ATC-STD-COMPAT-001"]),
], note="Keine Standard-Slots, sondern Release-Readiness-Gates gem. FRAMEWORK-001 §7"),
F("FAM-11", "Blockchain Standards", "ATC-STD-180..198", [
    sl("ATC-STD-180", "Blockchain Architecture", S_NEU, None, "Referenz: a-townchain (L3), Kernel K14/K16"),
    sl("ATC-STD-181", "Node Standard"),
    sl("ATC-STD-182", "Consensus", S_NEU, None, "Kernel K16: DAG+PoH+Validator+Voting+Finality"),
    sl("ATC-STD-183", "PoW"),
    sl("ATC-STD-184", "PoS"),
    sl("ATC-STD-185", "PoH", S_NEU, None, "Kernel K16 PoH"),
    sl("ATC-STD-186", "Validator"),
    sl("ATC-STD-187", "Staking"),
    sl("ATC-STD-188", "Delegation"),
    sl("ATC-STD-189", "Slashing"),
    sl("ATC-STD-190", "Block"),
    sl("ATC-STD-191", "Transaction"),
    sl("ATC-STD-192", "Mempool"),
    sl("ATC-STD-193", "Fee Market"),
    sl("ATC-STD-194", "MEV Mitigation"),
    sl("ATC-STD-195", "Fork Handling"),
    sl("ATC-STD-196", "Chain Recovery"),
    sl("ATC-STD-197", "Genesis"),
    sl("ATC-STD-198", "Network Upgrade", S_VERWEIST, ["ATC-STD-UPDATE-001"], "Network-Upgrades laufen als UPD"),
]),
F("FAM-12", "Token Standards", "ATC-STD-200..211", [
    sl("ATC-STD-200", "ATC Token"),
    sl("ATC-STD-201", "Tokenomics", S_KONFLIKT, None, "Slot belegt durch ATC-STD-201 (Repository Structure, §30-eingefroren). Auflösung via SCR"),
    sl("ATC-STD-202", "Token Supply", S_KONFLIKT, None, "Slot belegt durch ATC-STD-202 (Repository Naming & Classification, §30-eingefroren). Auflösung via SCR"),
    sl("ATC-STD-203", "Emission", S_KONFLIKT, None, "Slot belegt durch ATC-STD-203 (Repository Security & Release, §30-eingefroren). Auflösung via SCR"),
    sl("ATC-STD-204", "Burning", S_KONFLIKT, None, "Slot belegt durch ATC-STD-204 (Dependency & Interface, §30-eingefroren). Auflösung via SCR"),
    sl("ATC-STD-205", "Minting"),
    sl("ATC-STD-206", "Staking Rewards"),
    sl("ATC-STD-207", "Treasury"),
    sl("ATC-STD-208", "Governance Token"),
    sl("ATC-STD-209", "Token Allocation"),
    sl("ATC-STD-210", "Vesting"),
    sl("ATC-STD-211", "Token Migration", S_VERWEIST, ["ATC-STD-COMPAT-001"], "Migration als COMPAT-Wiederherstellung"),
], note="Kollisionsblock 201-204: Repository-Familie bleibt unantastbar; Token-Slots rücken via SCR auf Ersatzslots"),
F("FAM-13", "Smart Contracts", "ATC-STD-220..230", [
    sl("ATC-STD-220", "Smart Contract Architecture", S_VERWEIST, SC),
    sl("ATC-STD-221", "Smart Contract Coding", S_VERWEIST, SC),
    sl("ATC-STD-222", "Contract Security", S_VERWEIST, SC),
    sl("ATC-STD-223", "Contract Testing", S_VERWEIST, SC),
    sl("ATC-STD-224", "Contract Upgradeability", S_VERWEIST, SC),
    sl("ATC-STD-225", "Contract Ownership", S_VERWEIST, SC),
    sl("ATC-STD-226", "Multisig", S_VERWEIST, SC, "Kernel K15 Multi-Sig als Referenzimplementierung"),
    sl("ATC-STD-227", "Contract Verification", S_VERWEIST, SC),
    sl("ATC-STD-228", "Contract Audit", S_VERWEIST, SC),
    sl("ATC-STD-229", "Emergency Pause", S_VERWEIST, SC),
    sl("ATC-STD-230", "Contract Migration", S_VERWEIST, SC),
], note="Abgedeckt durch ATC-STD-SC-001..020 (Smart Contract Standards Framework); je Slot Mapping bei Ausbau zu prüfen"),
F("FAM-14", "Interoperability", "ATC-STD-240..250", [
    sl("ATC-STD-240", "Interoperability"),
    sl("ATC-STD-241", "Bridge"),
    sl("ATC-STD-242", "Bridge Security"),
    sl("ATC-STD-243", "Cross-Chain Messaging"),
    sl("ATC-STD-244", "IBC"),
    sl("ATC-STD-245", "EVM Compatibility"),
    sl("ATC-STD-246", "Ethereum Integration"),
    sl("ATC-STD-247", "Solana Integration"),
    sl("ATC-STD-248", "Polygon Integration"),
    sl("ATC-STD-249", "BSC Integration"),
    sl("ATC-STD-250", "Bridge Recovery", S_VERWEIST, ["ATC-STD-COMPAT-001"]),
]),
F("FAM-15", "ZKP / Privacy", "ATC-STD-260..267", [
    sl("ATC-STD-260", "ZKP Architecture", S_VERWEIST, ZKP),
    sl("ATC-STD-261", "Proof Generation", S_VERWEIST, ZKP),
    sl("ATC-STD-262", "Proof Verification", S_VERWEIST, ZKP),
    sl("ATC-STD-263", "Circuit Standard", S_VERWEIST, ZKP),
    sl("ATC-STD-264", "Trusted Setup", S_VERWEIST, ZKP),
    sl("ATC-STD-265", "Privacy", S_VERWEIST, ZKP),
    sl("ATC-STD-266", "Identity Proof", S_VERWEIST, ZKP),
    sl("ATC-STD-267", "ZKP Audit", S_VERWEIST, ZKP),
], note="Abgedeckt durch ATC-STD-ZKP-001..010 (ZKP-Layer, AD-045)"),
F("FAM-16", "Oracle & External Data", "ATC-STD-270..276", [
    sl("ATC-STD-270", "Oracle Architecture"), sl("ATC-STD-271", "External Data"),
    sl("ATC-STD-272", "Data Verification"), sl("ATC-STD-273", "Oracle Consensus"),
    sl("ATC-STD-274", "Price Feeds"), sl("ATC-STD-275", "Oracle Failure"),
    sl("ATC-STD-276", "External API Binding"),
]),
F("FAM-17", "Identity & Reputation", "ATC-STD-280..286", [
    sl("ATC-STD-280", "Identity", S_NEU, None, "Kernel K6 DID als Referenzimplementierung"),
    sl("ATC-STD-281", "Decentralised Identity", S_VERWEIST, ["ATC-STD-000"], "ATC-03 Legacy (DID) als historische Basis"),
    sl("ATC-STD-282", "Wallet Identity"),
    sl("ATC-STD-283", "Reputation", S_NEU, None, "Kernel K15 Reputation als Referenz"),
    sl("ATC-STD-284", "Sybil Resistance"),
    sl("ATC-STD-285", "Identity Recovery"),
    sl("ATC-STD-286", "Credential Verification"),
]),
F("FAM-18", "Cybersecurity", "ATC-STD-300..313", [
    sl("ATC-STD-300", "Cybersecurity Framework", S_KONFLIKT, None, "Slot belegt durch ATC-STD-300 (Development Standard, §30-eingefroren). Auflösung via SCR: Cybersecurity-Familie auf 301+ bzw. eigenen Namensraum"),
    sl("ATC-STD-301", "Secure Development"),
    sl("ATC-STD-302", "Authentication"),
    sl("ATC-STD-303", "Authorisation"),
    sl("ATC-STD-304", "Key Management"),
    sl("ATC-STD-305", "Secrets", S_VERWEIST, ["ATC-STD-203"], "Secret-Scanning aktiv"),
    sl("ATC-STD-306", "Encryption", S_NEU, None, "Kernel K6b Ed25519 als Referenz"),
    sl("ATC-STD-307", "Network Security"),
    sl("ATC-STD-308", "Endpoint Security"),
    sl("ATC-STD-309", "Supply Chain Security"),
    sl("ATC-STD-310", "Dependency Security", S_VERWEIST, ["ATC-STD-204"], "Dependabot/CodeQL aktiv (AUD-2026-0002)"),
    sl("ATC-STD-311", "Vulnerability Management"),
    sl("ATC-STD-312", "Penetration Testing"),
    sl("ATC-STD-313", "Security Incident Response", S_VERWEIST, ["ATC-STD-UPDATE-001"], "Emergency-Prozess als Teilbasis"),
]),
F("FAM-19", "AI-Agent Standards", "ATC-STD-320..335", [
    sl("ATC-STD-320", "AI Agent Architecture", S_VERWEIST, AAS),
    sl("ATC-STD-321", "Agent Identity", S_VERWEIST, AAS),
    sl("ATC-STD-322", "Agent Role", S_VERWEIST, AAS),
    sl("ATC-STD-323", "Agent Permissions", S_VERWEIST, AAS),
    sl("ATC-STD-324", "Agent Context", S_VERWEIST, AAS),
    sl("ATC-STD-325", "Agent Memory", S_VERWEIST, AAS),
    sl("ATC-STD-326", "Agent Decision Making", S_VERWEIST, ["ATC-STD-AI-DECISION-001"]),
    sl("ATC-STD-327", "Agent Planning", S_VERWEIST, AAS),
    sl("ATC-STD-328", "Agent Execution", S_VERWEIST, AAS),
    sl("ATC-STD-329", "Agent Verification", S_VERWEIST, AAS),
    sl("ATC-STD-330", "Agent Handover", S_VERWEIST, AAS),
    sl("ATC-STD-331", "Agent Communication", S_VERWEIST, AAS),
    sl("ATC-STD-332", "Agent Logging", S_VERWEIST, AAS),
    sl("ATC-STD-333", "Agent Audit", S_VERWEIST, ["ATC-STD-AUDIT-001"]),
    sl("ATC-STD-334", "Agent Safety", S_VERWEIST, ["ATC-STD-AI-DECISION-001", "ATC-STD-MILESTONE-001"], "Human Gates + Kill-Switch-Dokumentation"),
    sl("ATC-STD-335", "Agent Failure Recovery", S_VERWEIST, ["ATC-STD-AI-DECISION-001"]),
], note="Abgedeckt durch ATC-AAS-001..025 + ATC-STD-AI-DECISION-001 (über den Betriebsstandards)"),
F("FAM-20", "Agent Operating (KI-Softwareentwicklungsagent)", "ATC-STD-AOS-001 (reserviert)", [
    sl("ATC-STD-AOS-001", "ATC Agent Operating Standard — 14 Session-Fragen (Wer bin ich? … Welcher Audit-Nachweis entsteht?)", S_BELEGT, ["ATC-STD-AOS-001"], "Erstellt via SCR-0022 (REQ-FW-009); Mandatsregel gilt seit FRAMEWORK-001 §8"),
], note="14 Fragen verbindlich je Agenten-Session gem. FRAMEWORK-001 §8 (REQ-FW-009)"),
F("FAM-21", "Mining Standards", "ATC-STD-340..350", [
    sl("ATC-STD-340", "Mining Architecture"), sl("ATC-STD-341", "Miner"),
    sl("ATC-STD-342", "Mining Manager"), sl("ATC-STD-343", "CPU Mining"),
    sl("ATC-STD-344", "GPU Mining"), sl("ATC-STD-345", "Mobile Mining"),
    sl("ATC-STD-346", "Mining Algorithms"), sl("ATC-STD-347", "Miner Plugins"),
    sl("ATC-STD-348", "Mining Rewards"), sl("ATC-STD-349", "Mining Security"),
    sl("ATC-STD-350", "Miner Monitoring"),
]),
F("FAM-22", "Wallet Standards", "ATC-STD-360..368", [
    sl("ATC-STD-360", "Wallet Architecture"), sl("ATC-STD-361", "Address"),
    sl("ATC-STD-362", "Key Management"), sl("ATC-STD-363", "Transaction Signing"),
    sl("ATC-STD-364", "Wallet Recovery"), sl("ATC-STD-365", "Hardware Wallet"),
    sl("ATC-STD-366", "Wallet Security"), sl("ATC-STD-367", "Wallet UI"),
    sl("ATC-STD-368", "Burning Wallet"),
]),
F("FAM-23", "DeFi Standards", "ATC-STD-380..389", [
    sl("ATC-STD-380", "DeFi Architecture"), sl("ATC-STD-381", "DEX"),
    sl("ATC-STD-382", "Liquidity"), sl("ATC-STD-383", "Liquidity Pools"),
    sl("ATC-STD-384", "Staking"), sl("ATC-STD-385", "Lending"),
    sl("ATC-STD-386", "Yield"), sl("ATC-STD-387", "Oracle"),
    sl("ATC-STD-388", "DeFi Risk"), sl("ATC-STD-389", "DeFi Security"),
]),
F("FAM-24", "NFT / Marketplace", "ATC-STD-400..409", [
    sl("ATC-STD-400", "NFT Architecture"), sl("ATC-STD-401", "NFT Metadata"),
    sl("ATC-STD-402", "NFT Minting"), sl("ATC-STD-403", "NFT Ownership"),
    sl("ATC-STD-404", "NFT Transfer"), sl("ATC-STD-405", "NFT Marketplace"),
    sl("ATC-STD-406", "NFT Royalties"), sl("ATC-STD-407", "NFT Storage"),
    sl("ATC-STD-408", "NFT Verification"), sl("ATC-STD-409", "NFT Security"),
]),
F("FAM-25", "GameFi / Shivamon", "ATC-STD-420..434", [
    sl("ATC-STD-420", "GameFi Architecture"), sl("ATC-STD-421", "Shivamon"),
    sl("ATC-STD-422", "Game Economy"), sl("ATC-STD-423", "PvE"),
    sl("ATC-STD-424", "PvP"), sl("ATC-STD-425", "Guild"),
    sl("ATC-STD-426", "Alliance"), sl("ATC-STD-427", "Territory"),
    sl("ATC-STD-428", "Crafting"), sl("ATC-STD-429", "Mods"),
    sl("ATC-STD-430", "DNA"), sl("ATC-STD-431", "Evolution"),
    sl("ATC-STD-432", "Genesis"), sl("ATC-STD-433", "Game Assets"),
    sl("ATC-STD-434", "Game Blockchain Integration"),
], note="L6 genesis-engine/genesis-chronicles als Referenz; ATC-41+-Visionseinordnung beachten"),
F("FAM-26", "API Standards", "ATC-STD-440..450", [
    sl("ATC-STD-440", "API Architecture"), sl("ATC-STD-441", "REST API"),
    sl("ATC-STD-442", "GraphQL"), sl("ATC-STD-443", "RPC"),
    sl("ATC-STD-444", "WebSocket"), sl("ATC-STD-445", "Authentication"),
    sl("ATC-STD-446", "API Versioning", S_VERWEIST, ["ATC-STD-VERSION-001"]),
    sl("ATC-STD-447", "Rate Limiting", S_NEU, None, "Kernel K15 Rate-Limit als Referenz"),
    sl("ATC-STD-448", "API Errors"), sl("ATC-STD-449", "API Security"),
    sl("ATC-STD-450", "API Documentation"),
]),
F("FAM-27", "Datenstandards", "ATC-STD-460..469", [
    sl("ATC-STD-460", "Data Architecture"), sl("ATC-STD-461", "Data Model"),
    sl("ATC-STD-462", "Data Validation"), sl("ATC-STD-463", "Data Integrity"),
    sl("ATC-STD-464", "Data Versioning", S_VERWEIST, ["ATC-STD-VERSION-001"]),
    sl("ATC-STD-465", "Data Migration", S_VERWEIST, ["ATC-STD-COMPAT-001"]),
    sl("ATC-STD-466", "Database"), sl("ATC-STD-467", "Firestore"),
    sl("ATC-STD-468", "Backup"), sl("ATC-STD-469", "Data Recovery"),
]),
F("FAM-28", "Observability", "ATC-STD-480..488", [
    sl("ATC-STD-480", "Observability"), sl("ATC-STD-481", "Logging"),
    sl("ATC-STD-482", "Metrics"), sl("ATC-STD-483", "Tracing"),
    sl("ATC-STD-484", "Monitoring"), sl("ATC-STD-485", "Alerting"),
    sl("ATC-STD-486", "Health Checks"), sl("ATC-STD-487", "Audit Logs", S_VERWEIST, ["ATC-STD-AUDIT-001"]),
    sl("ATC-STD-488", "Performance Monitoring"),
]),
F("FAM-29", "Incident & Recovery", "ATC-STD-500..509", [
    sl("ATC-STD-500", "Incident Management"), sl("ATC-STD-501", "Incident Classification"),
    sl("ATC-STD-502", "Incident Response"), sl("ATC-STD-503", "Emergency Response", S_VERWEIST, ["ATC-STD-UPDATE-001"], "Emergency-Prozess UPD"),
    sl("ATC-STD-504", "Disaster Recovery"), sl("ATC-STD-505", "Fault Recovery"),
    sl("ATC-STD-506", "Rollback", S_VERWEIST, ["ATC-STD-UPDATE-001"]),
    sl("ATC-STD-507", "Failover"), sl("ATC-STD-508", "Backup Recovery"),
    sl("ATC-STD-509", "Business/System Continuity"),
]),
F("FAM-30", "Release & Update Standards", "ATC-STD-520..529", [
    sl("ATC-STD-520", "Release Management", S_VERWEIST, ["ATC-STD-VERSION-001", "ATC-STD-UPDATE-001"]),
    sl("ATC-STD-521", "Release Candidate", S_VERWEIST, ["ATC-STD-UPDATE-001"]),
    sl("ATC-STD-522", "Release Gate", S_VERWEIST, ["ATC-STD-UPDATE-001"], "UPD-G01..G09"),
    sl("ATC-STD-523", "Compatibility Check", S_VERWEIST, ["ATC-STD-COMPAT-001"]),
    sl("ATC-STD-524", "Major Update", S_VERWEIST, ["ATC-STD-UPDATE-001", "ATC-STD-COMPAT-001"], "UPD-G04 + MAJOR-Gate"),
    sl("ATC-STD-525", "Minor Update", S_VERWEIST, ["ATC-STD-UPDATE-001"]),
    sl("ATC-STD-526", "Patch", S_VERWEIST, ["ATC-STD-UPDATE-001"]),
    sl("ATC-STD-527", "Migration", S_VERWEIST, ["ATC-STD-COMPAT-001"]),
    sl("ATC-STD-528", "Rollback", S_VERWEIST, ["ATC-STD-UPDATE-001"]),
    sl("ATC-STD-529", "Post-Release Audit", S_VERWEIST, ["ATC-STD-UPDATE-001", "ATC-STD-AUDIT-001"]),
], note="Major-Version-Regel (13-Stufen-Prüfkette nach MAJOR) verbindlich via REQ-FW-008/COMPAT-001"),
F("FAM-31", "Projektmanagement", "ATC-STD-540..549", [
    sl("ATC-STD-540", "Project Management"),
    sl("ATC-STD-541", "Epic"), sl("ATC-STD-542", "Feature"),
    sl("ATC-STD-543", "Requirement"), sl("ATC-STD-544", "Task"),
    sl("ATC-STD-545", "TODO", S_NEU, None, "KaiOsTodo-Entity als Bestandspraxis"),
    sl("ATC-STD-546", "Sprint", S_NEU, None, "Sprint ≠ Meilenstein (MILESTONE-001 §9)"),
    sl("ATC-STD-547", "Milestone", S_VERWEIST, ["ATC-STD-MILESTONE-001"]),
    sl("ATC-STD-548", "Roadmap", S_VERWEIST, ["ATC-STD-MILESTONE-001"], "AD-027 als Bestands-Roadmap"),
    sl("ATC-STD-549", "Definition of Done", S_VERWEIST, ["ATC-STD-MILESTONE-001"], "§14 18-Punkte-DoD"),
]),
F("FAM-32", "Requirements Engineering", "ATC-STD-560..566", [
    sl("ATC-STD-560", "Requirements"),
    sl("ATC-STD-561", "Functional Requirements"),
    sl("ATC-STD-562", "Non-Functional Requirements"),
    sl("ATC-STD-563", "Acceptance Criteria", S_VERWEIST, ["ATC-STD-MILESTONE-001"]),
    sl("ATC-STD-564", "Requirement Traceability", S_VERWEIST, ["ATC-STD-AUDIT-001"]),
    sl("ATC-STD-565", "Requirement Changes", S_VERWEIST, ["ATC-STD-UPDATE-001"]),
    sl("ATC-STD-566", "Requirement Validation"),
]),
F("FAM-33", "UI/UX", "ATC-STD-580..587", [
    sl("ATC-STD-580", "UI/UX"), sl("ATC-STD-581", "Design System"),
    sl("ATC-STD-582", "Component Standard"), sl("ATC-STD-583", "Accessibility"),
    sl("ATC-STD-584", "Responsive Design"), sl("ATC-STD-585", "UX Consistency"),
    sl("ATC-STD-586", "Error UI"), sl("ATC-STD-587", "Admin UI"),
], note="Desktop-Editions nutzen egui (DESKTOP-S2..S5)"),
F("FAM-34", "Mobile / Desktop / OS", "ATC-STD-600..607", [
    sl("ATC-STD-600", "Platform Architecture"),
    sl("ATC-STD-601", "Mobile"),
    sl("ATC-STD-602", "Desktop", S_NEU, None, "atc-windows-edition/atc-linux-edition, egui"),
    sl("ATC-STD-603", "Globus OS", S_NEU, None, "globus-os (L4), AD-026"),
    sl("ATC-STD-604", "Shiva OS", S_NEU, None, "atc-shivacore Kernel (L1) — OS-Standard: Rust no_std"),
    sl("ATC-STD-605", "Aurora OS", S_NEU, None, "aurora-ai (L2)"),
    sl("ATC-STD-606", "Device Integration"),
    sl("ATC-STD-607", "Offline Mode"),
]),
F("FAM-35", "ATCLang", "ATC-STD-620..629", [
    sl("ATC-STD-620", "ATCLang Architecture", S_NEU, None, "atclang (L0), AD-022 Gates G1-G6"),
    sl("ATC-STD-621", "ATCLang Syntax", S_VERWEIST, ["ATC-STD-000"], "G1 Language Specification als Bestandspraxis"),
    sl("ATC-STD-622", "ATCLang Specification", S_VERWEIST, ["ATC-STD-000"], "G1 SPEC.md + registry.json"),
    sl("ATC-STD-623", "Compiler", S_NEU, None, "compile_source-Referenzpipeline"),
    sl("ATC-STD-624", "VM", S_NEU, None, "ATVM (atc-vm, L0)"),
    sl("ATC-STD-625", "REPL"),
    sl("ATC-STD-626", "Package System"),
    sl("ATC-STD-627", "Standard Library"),
    sl("ATC-STD-628", "Compatibility", S_VERWEIST, ["ATC-STD-COMPAT-001"]),
    sl("ATC-STD-629", "Language Versioning", S_VERWEIST, ["ATC-STD-VERSION-001"]),
]),
F("FAM-36", "AuditTrail / LogChain", "ATC-STD-640..646", [
    sl("ATC-STD-640", "AuditTrail", S_NEU, None, "Kernel K15 security_audit als Referenz"),
    sl("ATC-STD-641", "LogChain"), sl("ATC-STD-642", "Immutable Audit Log", S_VERWEIST, ["ATC-STD-AUDIT-001"]),
    sl("ATC-STD-643", "Event Recording"), sl("ATC-STD-644", "Evidence", S_VERWEIST, ["ATC-STD-MILESTONE-001"]),
    sl("ATC-STD-645", "Audit Correlation", S_VERWEIST, ["ATC-STD-AUDIT-001"]),
    sl("ATC-STD-646", "Audit Retention"),
]),
F("FAM-37", "Supply Chain & Dependencies", "ATC-STD-660..667", [
    sl("ATC-STD-660", "Software Supply Chain"),
    sl("ATC-STD-661", "Dependency Management", S_VERWEIST, ["ATC-STD-204"]),
    sl("ATC-STD-662", "Dependency Pinning"),
    sl("ATC-STD-663", "Vulnerability Scanning", S_VERWEIST, ["ATC-STD-203"], "Dependabot/CodeQL aktiv (F-025/#95)"),
    sl("ATC-STD-664", "SBOM"),
    sl("ATC-STD-665", "Third-Party Software"),
    sl("ATC-STD-666", "License Compliance"),
    sl("ATC-STD-667", "Artifact Integrity"),
]),
F("FAM-38", "Open Source & Lizenzierung", "ATC-STD-680..686", [
    sl("ATC-STD-680", "Open Source"), sl("ATC-STD-681", "License"),
    sl("ATC-STD-682", "Contributor"), sl("ATC-STD-683", "CLA"),
    sl("ATC-STD-684", "Code of Conduct"), sl("ATC-STD-685", "Security Disclosure"),
    sl("ATC-STD-686", "Vulnerability Disclosure"),
]),
F("FAM-39", "Business / Economics", "ATC-STD-700..706", [
    sl("ATC-STD-700", "Business Model"), sl("ATC-STD-701", "Treasury"),
    sl("ATC-STD-702", "Revenue"), sl("ATC-STD-703", "Cost Management"),
    sl("ATC-STD-704", "Incentive Alignment"), sl("ATC-STD-705", "Economic Security"),
    sl("ATC-STD-706", "Sustainability"),
]),
F("FAM-40", "Master-Audit", "ATC-STD-999 (reserviert)", [
    sl("ATC-STD-999", "Enterprise Completeness & Consistency Audit", S_BELEGT, ["ATC-STD-999", "ATC-STD-AUDIT-001"], "Erstellt via SCR-0022 (REQ-FW-010); AUD-Record Typ MASTER als Erweiterung von AUDIT-001"),
]),
F("FAM-41", "Repository Audit", "ATC-STD-REPO-AUDIT-001..003", [
    sl("ATC-STD-REPO-AUDIT-001", "ATC Repository Audit Standard", S_BELEGT, ["ATC-STD-REPO-AUDIT-001"]),
    sl("ATC-STD-REPO-AUDIT-002", "Audit-Checklisten- und Health-Score-Standard (CHECK-001, CHECK-002, …)", S_BELEGT, ["ATC-STD-REPO-AUDIT-002"], "Automatisierbare Checks + standardisierter Repository Health Score; erstellt via SCR-0021"),
    sl("ATC-STD-REPO-AUDIT-003", "Automatisierter ATC Repository Auditor (KI-/Automatisierungsagent)", S_GEPLANT, ["ATC-STD-REPO-AUDIT-001"], "Agent-Spezifikation (AAS-Kopplung); P2"),
], note="Neuer Namensraum gem. FRAMEWORK-001 §6.3 (BUG-/SC-/AAS-Muster); SCR-0020"),
F("FAM-42", "Protocol Standards", "ATC-STD-PROTOCOL-001..003", [
    sl("ATC-STD-PROTOCOL-001", "ATC Protocol Standards Dachstandard (Identität, Versionierung, Nachrichten, Sicherheit, Fehler, Kompatibilität, Governance, Auditing)", S_BELEGT, ["ATC-STD-PROTOCOL-001"]),
    sl("ATC-STD-PROTOCOL-002", "Protocol Conformance- & Interoperabilitäts-Test-Standard", S_GEPLANT, ["ATC-STD-PROTOCOL-001"], "Test-Suiten je ATC-PROTO-Familie; P2"),
    sl("ATC-STD-PROTOCOL-003", "Protocol Threat-Model- & Security-Audit-Standard", S_GEPLANT, ["ATC-STD-PROTOCOL-001"], "Vertiefung §11; P2"),
], note="Neuer Namensraum gem. FRAMEWORK-001 §6.3; ATC-PROTO-Registry (26 Familien) via SCR-0023"),
F("FAM-43", "Standards Governance Core", "ATC-STD-TAXONOMY-001 + STDDEV/REGISTRY/CHANGE-001", [
    sl("ATC-STD-TAXONOMY-001", "ATC Standards Taxonomy & Family Creation Standard (vierstufige Taxonomie, FAM-/CAT-REQ/TCR, TAX-CHECK-001..018)", S_BELEGT, ["ATC-STD-TAXONOMY-001"]),
    sl("ATC-STD-STDDEV-001", "Standards-Development-Standard (Erstellung/Review-Freigabe von Standards)", S_GEPLANT, ["ATC-STD-DESC-001"], "Governance Core; P1"),
    sl("ATC-STD-REGISTRY-001", "Registry-Management-Standard (SSOT-Verwaltung aller ATC-Registries)", S_GEPLANT, ["ATC-STD-TAXONOMY-001"], "Governance Core; P1"),
    sl("ATC-STD-CHANGE-001", "Change-Control-Dachnorm (konsolidiert ATC-STD-000 §19-33 + UPDATE-001 + COMPAT-001)", S_GEPLANT, ["ATC-STD-UPDATE-001", "ATC-STD-COMPAT-001"], "Governance Core; P1 — Abgrenzung bei Erstellung klaeren"),
], note="Standards Governance Core gem. Owner-Vorgabe 08.09.; TAXONOMY-001 via SCR-0024; Taxonomie-Registry (5 Domains, 33 Familien) S-24-geprueft"),
]

# Validierung der Daten: globale Slot-IDs eindeutig, Statistiken
seen = {}
stats = {}
for fam in FAMILIES:
    for s in fam["slots"]:
        assert s["id"] not in seen, f"Doppelte Slot-ID: {s['id']}"
        seen[s["id"]] = fam["id"]
        stats[s["status"]] = stats.get(s["status"], 0) + 1

total = sum(stats.values())
data = {
    "framework": {
        "standard": "ATC-STD-FRAMEWORK-001",
        "version": "1.0.0",
        "generated": "2026-09-07",
        "note": "ATC Enterprise Standards Framework Katalog — SSOT der Slot-Zuordnung (SCR-0019). Status: BELEGT/VERWEIST = durch Bestand abgedeckt, KONFLIKT = Slot kollidiert mit §30-ID, GEPLANT = reserviert, NEU = Lücke (via SCR zu erstellen). Regenerierung nur via SCR (REQ-FW-012).",
        "stats": {
            "families": len(FAMILIES),
            "slots_total": total,
            "slots_neu": stats.get("NEU", 0),
            "slots_verweist": stats.get("VERWEIST", 0),
            "slots_belegt": stats.get("BELEGT", 0),
            "slots_konflikt": stats.get("KONFLIKT", 0),
            "slots_geplant": stats.get("GEPLANT", 0),
        },
        "families": FAMILIES,
    }
}
with open("registry/framework.yaml", "w", encoding="utf-8") as fh:
    fh.write("# ATC Enterprise Standards Framework Katalog — ATC-STD-FRAMEWORK-001 §5 (SSOT)\n")
    fh.write("# Generiert von tools/framework/gen_framework.py — Änderungen nur via SCR (REQ-FW-012).\n")
    yaml.dump(data, fh, allow_unicode=True, sort_keys=False, width=200)

print(f"framework.yaml: {len(FAMILIES)} Familien, {total} Slots — {stats}")
