#!/usr/bin/env python3
"""generate_views.py — Generierte Views aus der Registry (ATC-STD-IMPLEMENTATION-001 §5, REQ-IMP-006).

Quelle: registry/standards.yaml (SSOT) + registry/framework.yaml + Dateisystem.
Erzeugt/aktualisiert:
  1. README.md     — Registry-Kennzahlen-Block (GENERATED) + Inline-Zaehler-Patches
  2. AGENT_MANIFEST.md — generierte Registry-Stand-Zeile
  3. STATUS.md     — generierter Snapshot-Banner (Interpretationsregel vs. Audit-Trail)
  4. registry/registry.lock — SHA-256 + Revision der Registry
Idempotent: wiederholte Ausfuehrungen erzeugen denselben Zustand.
Manuelle Zaehler in README/Manifest/STATUS sind verboten (REQ-IMP-006).
"""
import hashlib, os, re, subprocess, sys
from datetime import datetime, timezone, timedelta

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REG = os.path.join(ROOT, "registry", "standards.yaml")

def counts():
    total = approved = candidate = other = 0
    for line in open(REG, encoding="utf-8"):
        if line.strip().startswith("- {id: ATC"):
            total += 1
            m = re.search(r"status: (\w+)", line)
            s = m.group(1) if m else "?"
            if s == "approved": approved += 1
            elif s == "candidate": candidate += 1
            else: other += 1
    return total, approved, candidate, other


def std_index():
    """Registry-Lookup (SCR-0091): id -> {version, status} — KEINE hartcodierten Versionen/Statusse."""
    idx = {}
    for line in open(REG, encoding="utf-8"):
        m = re.search(r'- \{id: (ATC-[A-Z0-9-]+),.*?version: "?([\d.]+)"?, status: (\w+)', line)
        if m:
            idx[m.group(1)] = {"version": m.group(2), "status": m.group(3)}
    return idx

def git_sha():
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    except Exception:
        return "unknown"

def main():
    total, approved, candidate, other = counts()
    fam_count = sum(1 for l in open(os.path.join(ROOT, "registry", "framework.yaml"), encoding="utf-8") if re.match(r"\s*- id: FAM-\d+", l))
    std_files = sum(1 for dp, _, fs in os.walk(os.path.join(ROOT, "standards")) for f in fs if f.endswith(".md"))
    sha = hashlib.sha256(open(REG, "rb").read()).hexdigest()
    now = datetime.now(timezone(timedelta(hours=2))).strftime("%Y-%m-%d %H:%M UTC+2")

    sidx = std_index()
    regver = sidx.get("ATC-STD-REGISTRY-001", {}).get("version", "n/a (Identitaet: SHA-256)")
    # ---------- 4. registry.lock ----------
    lock = (f"# GENERATED by tools/gen_views/generate_views.py — nicht manuell bearbeiten (ATC-STD-IMPLEMENTATION-001 §5)\n"
            f"registry:\n  version: {regver}\n  commit: {git_sha()}\n  sha256: {sha}\n"
            f"  standards_total: {total}\n  standards_approved: {approved}\n  standards_candidate: {candidate}\n"
            f"  families: {fam_count}\n  generated_at: \"{now}\"\n")
    open(os.path.join(ROOT, "registry", "registry.lock"), "w").write(lock)

    stamp = f"<!-- GENERATED-BY generate_views.py — NICHT MANUELL BEARBEITEN -->"
    kb = (f"{stamp}\n"
          f"## Registry-Kennzahlen (GENERIERT — Quelle: `registry/standards.yaml`)\n\n"
          f"| Kennzahl | Wert |\n|---|---|\n"
          f"| Registry Standards | **{total}** |\n"
          f"| Registry APPROVED | **{approved}** |\n"
          f"| Registry CANDIDATE (§33) | **{candidate}** |\n"
          f"| Standard-Dateien (`standards/`) | **{std_files}** |\n"
          f"| Familien | **{fam_count}** |\n"
          f"| Registry SHA-256 | `{sha[:16]}…` (vollständig: `registry/registry.lock`) |\n"
          f"| Stand | {now} |\n\n"
          f"Implementierungs-Matrix: [`registry/standard-implementation.yaml`]({ROOT and 'registry/standard-implementation.yaml'}) (ATC-STD-IMPLEMENTATION-001).\n")

    # ---------- 1. README (SCR-0090/ATC-STD-003: VOLLREGENERATION aus Template) ----------
    p = os.path.join(ROOT, "README.md")
    tpl = open(os.path.join(ROOT, "tools", "gen_views", "README.template.md"), encoding="utf-8").read()
    state_id = f"ATC-STATE-{now[:10].replace('-', '')}-{sha[:8]}"
    date_compact = now[:10].replace("-", "")
    kpi = {"enforced": 0, "implemented": 0, "specification_only": 0}
    try:
        import yaml as _y
        _impl = _y.safe_load(open(os.path.join(ROOT, "registry", "standard-implementation.yaml"), encoding="utf-8"))
        for _s in _impl.get("standards", []):
            _st = _s.get("implementation", {}).get("status", "specification_only")
            kpi[_st] = kpi.get(_st, 0) + 1
    except Exception as _e:
        print(f"  Hinweis: KPI-Daten nicht verfuegbar ({_e})")
    def _st(i):
        s = sidx.get(i)
        if not s:
            return "| " + i + " | — | NICHT IN REGISTRY |"
        em = {"approved": "✅", "candidate": "🔶", "draft": "📝"}.get(s["status"], "")
        extra = " (Verfassung; Bootstrap-EXEMPT mit Sunset, ATC-STD-003 \u00a76)" if i == "ATC-STD-000" else (" (Governance Determinism & SSOT Matrix)" if i == "ATC-STD-003" else "")
        return "| " + i + " | " + s["version"] + " | " + em + " " + s["status"].upper() + extra + " |"
    comptable = "\n".join(_st(i) for i in ["ATC-STD-000", "ATC-STD-003", "ATC-STD-201",
        "ATC-STD-202", "ATC-STD-203", "ATC-STD-204", "ATC-STD-README-001"])
    v000 = sidx.get("ATC-STD-000", {})
    repover = "n/a"
    try:
        import yaml as _y2
        _repo = _y2.safe_load(open(os.path.join(ROOT, ".atc", "repository.yaml"), encoding="utf-8")) or {}
        repover = ((_repo.get("project", {}) or {}).get("version")
                   or _repo.get("standard_version") or "n/a")
    except Exception:
        pass
    for tok, val in {
        "@@STAMP@@": stamp, "@@STD@@": "ATC-STD-003", "@@DATE@@": date_compact, "@@SHA8@@": sha[:8],
        "@@NOW@@": now, "@@SHA@@": sha, "@@REGVER@@": regver, "@@TOTAL@@": str(total),
        "@@APPROVED@@": str(approved), "@@CANDIDATE@@": str(candidate), "@@OTHER@@": str(other),
        "@@FILES@@": str(std_files), "@@FAMS@@": str(fam_count),
        "@@ENF@@": str(kpi.get("enforced", 0)), "@@IMPL@@": str(kpi.get("implemented", 0)),
        "@@SPEC@@": str(kpi.get("specification_only", 0)),
        "@@VER000@@": v000.get("version", "n/a"),
        "@@ST000@@": v000.get("status", "NICHT IN REGISTRY").upper(),
        "@@COMPTABLE@@": comptable, "@@REPOVER@@": str(repover),
    }.items():
        tpl = tpl.replace(tok, val)
    open(p, "w", encoding="utf-8").write(tpl)
    print("  README vollregeneriert (State-ID:", state_id + ")")

    # ---------- 2. AGENT_MANIFEST (SCR-0091: keine hartcodierten Verfassungs-Versionen) ----------
    p = os.path.join(ROOT, "AGENT_MANIFEST.md")
    c = open(p, encoding="utf-8").read()
    _v0 = sidx.get("ATC-STD-000", {})
    _v0s = (_v0.get("status") or "UNBEKANNT").upper()
    c = re.sub(r"ATC-STD-000 v[\d.]+ (?:APPROVED|CANDIDATE|DRAFT)",
               "ATC-STD-000 v" + _v0.get("version", "n/a") + " " + _v0s, c)
    line = (f"> **Registry-Stand (GENERIERT aus `registry/standards.yaml`):** {total} Standards — "
            f"{approved} APPROVED · {candidate} CANDIDATE · {fam_count} Familien · Stand {now} · SHA-256 `{sha[:12]}…`")
    if "**Registry-Stand (GENERIERT" in c:
        c = re.sub(r"> \*\*Registry-Stand \(GENERIERT[^\n]*", line, c)
    else:
        m = re.search(r"(^# .*\n)", c, re.M)
        c = c.replace(m.group(1), m.group(1) + line + "\n", 1)
    open(p, "w", encoding="utf-8").write(c)

    # ---------- 3. STATUS.md ----------
    p = os.path.join(ROOT, "STATUS.md")
    c = open(p, encoding="utf-8").read()
    banner = (f"{stamp}\n"
              f"> **GENERIERTER SNAPSHOT ({now}):** {total} Standards ({approved} APPROVED, {candidate} CANDIDATE), "
              f"{fam_count} Familien, Registry SHA-256 `{sha[:12]}…` — Quelle: `registry/standards.yaml`.\n"
              f"> **Interpretationsregel:** Dieser Snapshot = aktueller Zustand. Alles darunter ist "
              f"AUDIT-TRAIL (historische Zustaende, z.B. „105/105“, „110/110“, „121/121“ zum jeweiligen "
              f"Zeitpunkt) und darf NICHT als aktueller Stand gelesen werden. Historie: CHANGELOG.md; "
              f"Change-History: change-requests/SCR-*.md; Audit-Evidence: docs/audits/.\n\n")
    if "GENERATED-BY generate_views.py" in c:
        c = re.sub(r"<!-- GENERATED-BY generate_views\.py[\s\S]*?Audit-Evidence: docs/audits/\.\n\n", banner, c, count=1)
    else:
        m = re.search(r"(^# STATUS[^\n]*\n)", c, re.M)
        c = c.replace(m.group(1), m.group(1) + "\n" + banner, 1)
    open(p, "w", encoding="utf-8").write(c)

    # ---------- 4. .github/ai/agent.yaml (SCR-0053): required_standards SSOT-Sync ----------
    p = os.path.join(ROOT, ".github", "ai", "agent.yaml")
    if os.path.exists(p):
        man = open(p, encoding="utf-8").read()
        ids = re.findall(r"id:\s*(ATC-[A-Z0-9-]+)", open(os.path.join(ROOT, "registry", "standards.yaml"), encoding="utf-8").read())
        m2 = re.search(r"(required_standards:\n)((?:- .+\n)+)", man)
        if m2:
            new_block = m2.group(1) + "".join(f"- {i}\n" for i in ids)
            if man[m2.start():m2.end()] != new_block:
                man = man[:m2.start()] + new_block + man[m2.end():]
                open(p, "w", encoding="utf-8").write(man)
                print(f"✓ agent.yaml required_standards regeneriert: {len(ids)} Standards (SSOT-Sync)")

    print(f"✓ Views generiert: {total} Standards ({approved} APPROVED/{candidate} CANDIDATE), "
          f"{fam_count} Familien, {std_files} Dateien, SHA {sha[:12]}…")

if __name__ == "__main__":
    main()
