#!/usr/bin/env python3
"""generate_views.py — Generierte Views aus der Registry (ATC-STD-IMPLEMENTATION-001 §5, REQ-IMP-006).

Quelle: registry/standards.yaml (SSOT) + registry/framework.yaml + Dateisystem.
Erzeugt/aktualisiert:
  1. README.md     — Registry-Kennzahlen-Block (GENERATED) + Inline-Zaehler-Patches
  2. AGENT_MANIFEST.md — generierte Registry-Stand-Zeile
  3. STATUS.md     — generierter Snapshot-Banner (Interpretationsregel vs. Audit-Trail)
  4. registry/registry.lock — SHA-256 + Revision der Registry
Idempotent: wiederholte Ausfuehrungen erzeugen denselben Zustand.
Manuelle Zaehler in README/Manifest/STATUS sind verboten (REQ-IMP-006).
"""
import hashlib, os, re, subprocess, sys
from datetime import datetime, timezone, timedelta

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
REG = os.path.join(ROOT, "registry", "standards.yaml")

def counts():
    total = approved = candidate = other = 0
    for line in open(REG, encoding="utf-8"):
        if line.strip().startswith("- {id: ATC"):
            total += 1
            m = re.search(r"status: (\w+)", line)
            s = m.group(1) if m else "?"
            if s == "approved": approved += 1
            elif s == "candidate": candidate += 1
            else: other += 1
    return total, approved, candidate, other

def git_sha():
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    except Exception:
        return "unknown"

def main():
    total, approved, candidate, other = counts()
    fam_count = sum(1 for l in open(os.path.join(ROOT, "registry", "framework.yaml"), encoding="utf-8") if re.match(r"\s*- id: FAM-\d+", l))
    std_files = sum(1 for dp, _, fs in os.walk(os.path.join(ROOT, "standards")) for f in fs if f.endswith(".md"))
    sha = hashlib.sha256(open(REG, "rb").read()).hexdigest()
    now = datetime.now(timezone(timedelta(hours=2))).strftime("%Y-%m-%d %H:%M UTC+2")

    # ---------- 4. registry.lock ----------
    lock = (f"# GENERATED by tools/gen_views/generate_views.py — nicht manuell bearbeiten (ATC-STD-IMPLEMENTATION-001 §5)\n"
            f"registry:\n  version: 1.2.0\n  commit: {git_sha()}\n  sha256: {sha}\n"
            f"  standards_total: {total}\n  standards_approved: {approved}\n  standards_candidate: {candidate}\n"
            f"  families: {fam_count}\n  generated_at: \"{now}\"\n")
    open(os.path.join(ROOT, "registry", "registry.lock"), "w").write(lock)

    stamp = f"<!-- GENERATED-BY generate_views.py — NICHT MANUELL BEARBEITEN -->"
    kb = (f"{stamp}\n"
          f"## Registry-Kennzahlen (GENERIERT — Quelle: `registry/standards.yaml`)\n\n"
          f"| Kennzahl | Wert |\n|---|---|\n"
          f"| Registry Standards | **{total}** |\n"
          f"| Registry APPROVED | **{approved}** |\n"
          f"| Registry CANDIDATE (§33) | **{candidate}** |\n"
          f"| Standard-Dateien (`standards/`) | **{std_files}** |\n"
          f"| Familien | **{fam_count}** |\n"
          f"| Registry SHA-256 | `{sha[:16]}…` (vollständig: `registry/registry.lock`) |\n"
          f"| Stand | {now} |\n\n"
          f"Implementierungs-Matrix: [`registry/standard-implementation.yaml`]({ROOT and 'registry/standard-implementation.yaml'}) (ATC-STD-IMPLEMENTATION-001).\n")

    # ---------- 1. README ----------
    p = os.path.join(ROOT, "README.md")
    c = open(p, encoding="utf-8").read()
    c = re.sub(r"<!-- GENERATED-BY generate_views\.py[\s\S]*?ATC-STD-IMPLEMENTATION-001\)\.\n", "", c)  # alter Block weg
    # Inline-Zaehler-Patches (REQ-IMP-006: keine manuellen Zaehler)
    c = re.sub(r"aller \d+ registrierten Standards", f"aller {total} registrierten Standards", c)
    c = re.sub(r"\*\*\d+ Standards\**: \d+ APPROVED, \d+ offen", f"**{total} Standards**: {approved} APPROVED, {candidate} CANDIDATE", c)
    c = re.sub(r"\(\d+/\d+ \+ Gates\)", "(Registry-Validierung + Gates)", c)
    c = re.sub(r"CI-Validierung \(\d+/\d+ \+ Gates\)", "CI-Validierung (Registry-Validierung + Gates)", c)
    c = re.sub(r"# \d+/\d+ COMPLIANT", f"# {total}/{total} COMPLIANT", c)
    c = re.sub(r"\(\d+/\d+ COMPLIANT\)", f"({total}/{total} COMPLIANT)", c)
    c = re.sub(r"alle \d+ Standards APPROVED und normativ in Kraft", f"{approved} Standards APPROVED und normativ in Kraft, {candidate} CANDIDATE (§33)", c)
    c = re.sub(r"\d+ Standard-Dateien in \d+ Familien", f"{std_files} Standard-Dateien in {fam_count} Familien", c)
    c = re.sub(r"\d+ Standards in \d+ Verzeichnissen", f"{total} Standards in {fam_count} Verzeichnissen", c)
    c = re.sub(r"\d+ Standards in \d+ Familien, vollständige REQ-ID-Struktur", f"{total} Standards in {fam_count} Familien, vollständige REQ-ID-Struktur", c)
    # Kennzahlen-Block nach der ersten Ueberschrift einfuegen
    m = re.search(r"(^# .*\n)", c, re.M)
    if m and "GENERATED-BY generate_views.py" not in c:
        c = c.replace(m.group(1), m.group(1) + "\n" + kb, 1)
    elif "GENERATED-BY generate_views.py" not in c:
        c = kb + "\n" + c
    # Implementierungs-KPI (SCR-0052/P1-004): SSOT-generiert aus standard-implementation.yaml
    try:
        import yaml as _y
        _impl = _y.safe_load(open(os.path.join(ROOT, "registry", "standard-implementation.yaml"), encoding="utf-8"))
        _cnt = {}
        for _s in _impl.get("standards", []):
            _st = _s.get("implementation", {}).get("status", "specification_only")
            _cnt[_st] = _cnt.get(_st, 0) + 1
        _kpi = (f"**Implementierungs-KPI:** {total} Standards normativ definiert — "
                f"{_cnt.get('enforced', 0)} enforced, {_cnt.get('implemented', 0)} implemented, "
                f"{_cnt.get('specification_only', 0)} specification-only (Zielsysteme im qualitätsgetriebenen Rebuild AD-023/AD-045). "
                f"Die Aussage „{total} Standards implementiert“ ist unzulässig (SCR-0048).")
        if "**Implementierungs-KPI:**" in c:
            c = re.sub(r"\*\*Implementierungs-KPI:\*\*.*?unzulässig \(SCR-0048\)\.", _kpi, c)
        else:
            c = c.replace("[`registry/standard-implementation.yaml`](registry/standard-implementation.yaml) (ATC-STD-IMPLEMENTATION-001).",
                          "[`registry/standard-implementation.yaml`](registry/standard-implementation.yaml) (ATC-STD-IMPLEMENTATION-001)." + chr(10) + _kpi, 1)
    except Exception as _e:
        print(f"  Hinweis: Implementierungs-KPI nicht gepatcht ({_e})")
    c = re.sub(r"\n{3,}", "\n\n", c)  # Generator-Hygiene: idempotent, keine Leerzeilen-Akkumulation
    open(p, "w", encoding="utf-8").write(c)

    # ---------- 2. AGENT_MANIFEST ----------
    p = os.path.join(ROOT, "AGENT_MANIFEST.md")
    c = open(p, encoding="utf-8").read()
    line = (f"> **Registry-Stand (GENERIERT aus `registry/standards.yaml`):** {total} Standards — "
            f"{approved} APPROVED · {candidate} CANDIDATE · {fam_count} Familien · Stand {now} · SHA-256 `{sha[:12]}…`")
    if "**Registry-Stand (GENERIERT" in c:
        c = re.sub(r"> \*\*Registry-Stand \(GENERIERT[^\n]*", line, c)
    else:
        m = re.search(r"(^# .*\n)", c, re.M)
        c = c.replace(m.group(1), m.group(1) + line + "\n", 1)
    open(p, "w", encoding="utf-8").write(c)

    # ---------- 3. STATUS.md ----------
    p = os.path.join(ROOT, "STATUS.md")
    c = open(p, encoding="utf-8").read()
    banner = (f"{stamp}\n"
              f"> **GENERIERTER SNAPSHOT ({now}):** {total} Standards ({approved} APPROVED, {candidate} CANDIDATE), "
              f"{fam_count} Familien, Registry SHA-256 `{sha[:12]}…` — Quelle: `registry/standards.yaml`.\n"
              f"> **Interpretationsregel:** Dieser Snapshot = aktueller Zustand. Alles darunter ist "
              f"AUDIT-TRAIL (historische Zustaende, z.B. „105/105“, „110/110“, „121/121“ zum jeweiligen "
              f"Zeitpunkt) und darf NICHT als aktueller Stand gelesen werden. Historie: CHANGELOG.md; "
              f"Change-History: change-requests/SCR-*.md; Audit-Evidence: docs/audits/.\n\n")
    if "GENERATED-BY generate_views.py" in c:
        c = re.sub(r"<!-- GENERATED-BY generate_views\.py[\s\S]*?Audit-Evidence: docs/audits/\.\n\n", banner, c, count=1)
    else:
        m = re.search(r"(^# STATUS[^\n]*\n)", c, re.M)
        c = c.replace(m.group(1), m.group(1) + "\n" + banner, 1)
    open(p, "w", encoding="utf-8").write(c)

    print(f"✓ Views generiert: {total} Standards ({approved} APPROVED/{candidate} CANDIDATE), "
          f"{fam_count} Familien, {std_files} Dateien, SHA {sha[:12]}…")

if __name__ == "__main__":
    main()
