name: Ruff Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    uses: A-TownChain-Okosystems/.github/.github/workflows/reusable-ruff.yml@b2d84765eba25a0d1e67ffdf21e9fdbd37d058b6
    permissions:
      contents: read
