name: Ruff Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    uses: A-TownChain-Okosystems/.github/.github/workflows/reusable-ruff.yml@856769983e6e9342a2588140f127c5ad5a612f2d
    permissions:
      contents: read
